config/routes.rb
Rails.application.routes.draw do
  
  resources :notifications
  resources :comments
  get 'contracts/:id/add' => "contracts#add", as: :add_contract
  get 'contracts/:id/destroy' => "contracts#destroy", as: :destroy_contract
  get 'contracts/:id/start' => "contracts#start", as: :start_contract
  get 'contracts/:id/reset' => "contracts#reset", as: :reset_contract
  get 'contracts/:id/approve' => "contracts#approve", as: :approve_contract
  get 'contracts/:id/finish' => "contracts#finish", as: :finish_contract
  get 'contracts/search' => "contracts#search", as: :search_contract
  get 'profiles/search' => "profiles#search", as: :search_users 
  get 'profiles/progress' => "profiles#progressing", as: :progressing_profiles
  get 'profiles/saved' => "profiles#saved", as: :saved_profiles
  resources :profiles do
    get :autocomplete_skill_tag_name, on: :collection
    get :autocomplete_industry_tag_name, on: :collection
  end

  resources :contracts do
    get :autocomplete_skill_tag_name, on: :collection
  end

  get 'skill_tags/:id/add' => "skill_tags#add", as: :add_skill_tag
  
  devise_for :users, :controllers => { :registrations => "registrations" }
  devise_scope :user do
    get "/login" => "devise/sessions#new"
    delete "/logout" => "devise/sessions#destroy"
  end

  root 'profiles#index'

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  autocomplete :skill_tag, :name
  autocomplete :industry_tag, :name
  # GET /profiles
  # GET /profiles.json
  def index
  end

  def progressing
  end

  def saved
  end  

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @user = User.includes(:skill_tags,:industry_tags).find(params[:id])
    
  end

  # GET /profiles/new
  def new
  end

  # GET /profiles/1/edit
  def update
    @user = User.find(params[:id])

    
    if (current_user.is_student)
      if (!params[:skill_tag_name].nil?)
        result = params[:skill_tag_name].split(",")
        result.each do |k|
          skill = SkillTag.find_by_name(k)
          @user.skill_tags << skill
          @user.save!
        end
      end
    else
      if (!params[:industry_tag_name].nil?)
        result = params[:industry_tag_name].split(",")
        result.each do |k|
          industry = IndustryTag.find_by_name(k)
          @user.industry_tags << industry
          @user.save!
        end
      end
    end
    
      respond_to do |format|
      if @user.update(profile_params)
        format.html { redirect_to root_path, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end 
    end
  end

  # POST /profiles
  # POST /profiles.json
  def create
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def edit
    @user = User.find(params[:id])
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
  end

  def search
                if params[:search]
                          @users = User.search(params[:search]).order("created_at DESC").page(params[:page]).per(15)

                else
                          @users = User.all.order("created_at DESC").page(params[:page]).per(15)
                end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
    end

    # Never trust parameters from the scary internet, only allow the white list through.
   def profile_params
    params.require(:user).permit(:name, :email, :password, :first_name, :last_name, :corporation, :school, :image_url, :profile, :linkedin_url, :github_url, :personal_website, :company_website, :avatar)
   end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
    def cache_key_for_user_row(user)
      "user-#{user.id}-#{user.updated_at}"
    end
    def cache_key_for_users
      "users-#{User.maximum(:updated_at)}-#{User.count}"
    end
end

app/views/profiles/edit.html.erb
<%= javascript_include_tag "application" %>
<%= stylesheet_link_tag "application" %>

    <div class="container">    
        <div id="loginbox" style="margin-top:50px;" class="mainbox col-md-6 col-sm-8">                    
            <div class="panel panel-info" >
                    <div class="panel-heading">
                        <div class="panel-title">Customize Profile</div>
                    </div>     
                    <div style="padding-top:30px" class="panel-body" >
                      <div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
                      <%= form_for @user, url: profile_path(@user), html: { method: :put } do |f| %>

		      <% if current_user.is_student %>
                      <div style="margin-bottom: 25px" class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span> 
			<%= f.text_field :first_name, autofocus: true, class:"form-control", placeholder:"First Name" %>
                      </div>

		      <div style="margin-bottom: 25px" class="input-group">
                        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span> 
			<%= f.text_field :last_name, autofocus: true, class:"form-control", placeholder:"Last Name" %>
                      </div>
		      <% end %>

		      <% if (!current_user.is_student) %>
		    
		      <div style="margin-bottom: 25px" class="input-group">
			<span class="input-group-addon"><i class="glyphicon glyphicon-envolope"></i></span>
			<%= f.text_field :corporation, autocomplete: "off", class:"form-control", placeholder:"Corporation" %>
                      </div>

		      <div style="margin-bottom: 25px" class="input-group">
			<span class="input-group-addon"><i class="glyphicon glyphicon-globe"></i></span>
			<%= f.text_field :company_website, autocomplete: "off", class:"form-control", placeholder:"Website" %>
                      </div>
		      <div style="margin-bottom: 25px" class="input-group">
			<span class="input-group-addon"><i class="glyphicon glyphicon-shopping-card"></i></span>
			<%= autocomplete_field_tag :industry_tag_name, params[:name], autocomplete_industry_tag_name_profiles_path, 'data-delimiter' => ',', :multiple =>true, class:"form-control", placeholder:"Enter your Industries" %>
		
                      </div>
		     
  
		      <% else %>
		      <div style="margin-bottom: 25px" class="input-group">
			<span class="input-group-addon"><i class="glyphicon glyphicon-book"></i></span>
			<%= f.text_field :school, autocomplete: "off", class:"form-control", placeholder:"School" %>
                      </div>
		      <div style="margin-bottom: 25px" class="input-group">
			<span class="input-group-addon"><i class="glyphicon glyphicon-globe"></i></span>
			<%= f.text_field :linkedin_url, autocomplete: "off", class:"form-control", placeholder:"Linkedin Username" %>
                      </div>
		      <div style="margin-bottom: 25px" class="input-group">
			<span class="input-group-addon"><i class="glyphicon glyphicon-globe"></i></span>
			<%= f.text_field :github_url, autocomplete: "off", class:"form-control", placeholder:"Github Username" %>
                      </div>
		      <div style="margin-bottom: 25px" class="input-group">
			<span class="input-group-addon"><i class="glyphicon glyphicon-globe"></i></span>
			<%= f.text_field :personal_website, autocomplete: "off", class:"form-control", placeholder:"Personal Website" %>
                      </div>
		      <div style="margin-bottom: 25px" class="input-group">
			<span class="input-group-addon"><i class="glyphicon glyphicon-star"></i></span>
			<%= autocomplete_field_tag :skill_tag_name, params[:name], autocomplete_skill_tag_name_profiles_path, 'data-delimiter' => ',', :multiple =>true, class:"form-control", placeholder:"Enter your skills" %>
                      </div>
		      <% end %>  
                      <div style="margin-bottom: 25px" class="input-group">
			<span class="input-group-addon"><i class="glyphicon glyphicon-folder-open"></i></span>
			<%= f.file_field :avatar, autocomplete: "off", class:"form-control", placeholder:"Profile Image" %>
                      </div>
                                    

		      <div style="margin-bottom: 25px" class="input-group">
			<span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
			<%= f.text_area :profile, autocomplete: "off", rows: 10, class:"form-control", placeholder:"Profile" %>
                      </div>



                            <div style="margin-top:10px" class="form-group">
                              <!-- Button -->
                              <div class="col-sm-12 controls">
				<%= f.submit "Save",class:"btn btn-success" %>
                              </div>
                            </div>

			    <% end %>  
                            <div class="form-group">
                              <div class="col-md-12 control">
                                <div style="padding-top:15px; font-size:85%" >
				  <%= link_to "Back", :back %>
                             
</a>
</div>
</div>
</div>  




                        </div>                     
                    </div>  
        </div>
        
    </div>

app/views/profiles/index.html.erb
<% if (current_user.is_student) %>
    <h1 class="page-header">My Contracts</h1>

    <ul class="nav nav-pills">
        <li class="active"><a href="#">Finished Contracts</a></li>
        <li><a href="/profiles/progress">Live Contracts</a></li>
        <li><a href="/profiles/saved">Saved Contracts</a></li>
    </ul>
    <ul class="contracts-list finished">  
        <% current_user.contracts.each do |contract| %>
            <% if (contract.done == true && contract.worker == current_user.id) %>
                <li class="contract-li <%= cycle('contract-odd', 'contract-even') %>">
                <div class="contract-box">
                    <div class="contract-img">
                        <%= image_tag(contract.image_url, class: 'contract-image') %>
                    </div>
                    <div class="contract-text">
                        <h4 class="contract-title"><%= contract.title %></h4>
                        <div class="contract-description">
                            <h4><%= truncate(strip_tags(contract.description), length: 80) %></h4>
                            <%= link_to 'Show', contract, class:"btn btn-default btn-xs"%>
                        </div>
                    </div>
                </div>
                </li>
            <% end %>
        <% end %>
    </ul>
<% else %>

    <ul class="nav nav-pills">
        <li class="active"><a href="#">Pending Contracts</a></li>
        <li><a href="/profiles/progress">Progressing Contracts</a></li>
        <li><a href="/profiles/saved">Waiting Contracts</a></li>
    </ul>
    <tbody>
        <div id="Pending">   
            <% current_user.contracts.each do |p| %>
                <% if (p.done == true && p.approved == false) %>
                    <% p.users.each do |c| %>
                        <% if (p.worker == c.id)  %>
                            <p><strong><%= c.first_name %></strong> is awaiting your approval.</p>
                            <br/>
                            <%= link_to "Approve and finish contract", approve_contract_path(p),class:"btn btn-default btn-xs"%>
                        <% end %>
                    <% end %>
                <% end %>
            <%end%>
        </div>
    </tbody>
<% end %>

app/views/profiles/new.html.erb
<h2>Create Profile</h2>

<%= form_for @user, url: profile_path(@user), html: { method: :put } do |f| %>
  <%= devise_error_messages! %>

  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name, autofocus: true %> 
  </div>

  <% if (!current_user.is_student) %>
    <div class="field"> 
      <%= f.label :corporation %><br />
      <%= f.text_field :corporation, autofocus: true %>
    </div>
  <% else %>

    <div class="field">
      <%= f.label :school %><br />
      <%= f.text_field :school, autofocus: true %>
    </div>
  <% end %>

   <div class="field">
    <%= f.label :avatar %><br />
    <%= f.file_field :avatar %>
  </div> 
  <div class="field">
    <%= f.label :profile %><br />
    <%= f.text_area :profile, rows: 10, autofocus: true %>
  </div>

  <div class="actions">
    <%= f.submit "Submit" %>
  </div>

<% end %>

<%= link_to "Back", :back %>

app/views/profiles/progressing.html.erb
<% if (current_user.is_student) %>
    <h1 class="page-header">My Contracts</h1>

    <ul class="nav nav-pills">
        <li><a href="/profiles">Finished Contracts</a></li>
        <li class="active"><a href="#">Live Contracts</a></li>
        <li><a href="/profiles/saved">Saved Contracts</a></li>
    </ul>
    <ul class="contracts-list progressing">
        <% current_user.contracts.each do |contract| %>
            <% if (contract.done == false && contract.progress == true && current_user.id == contract.worker) %>
                <li class="contract-li <%= cycle('contract-odd', 'contract-even') %>">
                <div class="contract-box">
                    <div class="contract-img">
                        <%= image_tag(contract.image_url, class: 'contract-image') %>
                    </div>
                    <div class="contract-text">
                        <h4 class="contract-title"><%= contract.title %></h4>
                        <div class="contract-description">
                            <h4><%= truncate(strip_tags(contract.description), length: 80) %></h4>
                            <%= link_to 'Show', contract, class:"btn btn-default btn-xs"%>
                            <%= link_to 'Mark finished!', finish_contract_path(contract), {class: 'btn btn-primary btn-xs'}%> 
                        </div>
                    </div>
                </div>
                </li>   
            <% end %>
        <% end %>
    </ul>
<% else %>

    <ul class="nav nav-pills">
        <li><a href="/profiles">Pending Contracts</a></li>
        <li class="active"><a href="#">Progressing Contracts</a></li>
        <li><a href="/profiles/saved">Waiting Contracts</a></li>
    </ul>
    <tbody>
        <div id="Progress">
            <% current_user.contracts.each do |p| %>
                <% if (p.progress == true && p.done == false) %>
                    <h3><%= p.title %></h3>
                    <p class="contractdescription"><strong>Description:</strong> <%=p.description%></p>
                    <% p.users.each do |c| %>
                        <% if (p.worker == c.id) %>
                            <p><strong><%= c.first_name %></strong> is working on this contract.</p>
                            <br/>
                            <%= link_to "Drop Student", reset_contract_path(p),class:"btn btn-default btn-xs" %>
                        <% end %>
                    <% end %>
                <% end %>
            <%end%>
        </div>
    </tbody>    
<% end %>

app/views/profiles/saved.html.erb
<% if (current_user.is_student) %>
    <h1 class="page-header">My Contracts</h1>

    <ul class="nav nav-pills">
        <li><a href="/profiles">Finished Contracts</a></li>
        <li><a href="/profiles/progress">Live Contracts</a></li>
        <li class="active"><a href="#">Saved Contracts</a></li>
    </ul>
    <ul class="contract-list saved">
        <% current_user.contracts.each do |contract| %>
            <% if (contract.progress == false) %>
                <li class="contract-li <%= cycle('contract-odd', 'contract-even') %>">
                <div class="contract-box">
                    <div class="contract-img">
                        <%= image_tag(contract.image_url, class: 'contract-image') %>
                    </div>
                    <div class="contract-text">
                        <h3 class="contract-title"><%= contract.title %></h4>
                        <div class="contract-description">
                            <p><%= truncate(strip_tags(contract.description), length: 80) %></p>
                            <%= link_to 'Show', contract, class:"btn btn-default btn-xs"%>
                        </div>
                    </div>
                </div>
                </li>
            <% end %>
        <% end %>
    </ul>
<% else %>

    <ul class="nav nav-pills">
        <li><a href="/profiles">Pending Contracts</a></li>
        <li><a href="/profiles/progress">Progressing Contracts</a></li>
        <li class="active"><a href="#">Waiting Contracts</a></li>
    </ul>
    <tbody>
        <div id="Waiting">
            <% current_user.contracts.each do |p| %>
                <% if (p.progress == false) %>
                    <h3><%= p.title %></h3>
                    <p class="contractdescription"><strong>Description:</strong> <%=p.description%></p>
                    <p> There are currently <%= p.users.size-1 %> interested students.</p>
                    <%= link_to "See all users", contract_path(p) ,class:"btn btn-default btn-xs"%>
                    <%= link_to "Delete Contract", destroy_contract_path(p) ,class:"btn btn-default btn-xs"%>
                <% end %>
            <%end%>
        </div>  
    </tbody>
<% end %>

app/views/profiles/search.html.erb
<h1 class="page-header">Search Users</h1>
<%= form_tag(search_users_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Users" %>
    <%= submit_tag "Search" %>
<% end %>
<h2>Found <%= pluralize @users.total_count , "users" %>!</h2>
<hr/>
<ul class="contracts-list finished">
    <%= paginate @users, :theme => 'twitter-bootstrap-3' %>
    <% cache(cache_key_for_users) do %>
    <% @users.each do |user| %>
        <% cache(cache_key_for_user_row(user)) do %>
        <li class="contract-li <%= cycle('contract-odd', 'contract-even') %>">
        <div class="contract-box">
            <div class="row">
                <div class="col-sm-2">
            <div class="contract-img">
               <%= image_tag(user.avatar.url(:thumb)) %>             </div>
            </div>
            <div class="col-sm-10 contract-text">
                <% if user.is_student %>
                <h4 class="contract-title"><%= user.first_name %> <%= user.last_name %></h4>
                <% else %>
                <h4 class="contract-title"><%= user.corporation %></h4>
            <% end %>
                <div class="contract-description">
                    <h4><%= truncate(strip_tags(user.profile), length: 80) %></h4>
                    <%= link_to 'Show', profile_path(user), class:"btn btn-default btn-xs"%>
                </div>
            </div>
        </div>
        </li>
    <% end %>
    <% end %>
    <% end %>
</ul>

app/views/profiles/show.html.erb
<%= stylesheet_link_tag "show_profiles" %>
<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css" rel="stylesheet">
<div class="container">
	<div class="row">
		<div class="col-md-8 col-lg-6">
    	 <div class="well profile">
            <div class="col-sm-12">
                <div class="col-xs-12 col-sm-8">
		  <% if @user.is_student %>
                    <h2><%= @user.first_name %> <%= @user.last_name %> </h2>
                    <p><strong>School: </strong> <%= @user.school %> </p>
                    <p><strong>Profile: </strong> <%= @user.profile %> </p>
                    <p><strong>Skills: </strong>
		      <% @user.skill_tags.each do |k| %>
		      <span class="tags"><%= k.name %></span>
		      <% end %>
                    </p>
		  <% else %>
		  <h2><%= @user.corporation %> </h2>
                    <p><strong>Company Website: </strong><a href="https://<%= @user.company_website %>">Visit</a> </p>
                    <p><strong>Profile: </strong> <%= @user.profile %> </p>
                    <p><strong>Industry: </strong>
		      <% @user.industry_tags.each do |k| %>
		      <span class="tags"><%= k.name %></span>
		      <% end %>
                    </p>
		   <% end %>
                </div>             
                <div class="col-xs-12 col-sm-4 text-center">
                    <figure>
                      <%= image_tag(current_user.avatar.url(:thumb)) %>
                        <figcaption class="ratings">
                            <p>Ratings
                            <% ((@user.rating_value.to_i)/(@user.rating_count)).times do |x| %>
                            <a href="#">
                                <span class="fa fa-star"></span>
                            </a>
                        <% end%>
                            <% (5-(@user.rating_value.to_i)/(@user.rating_count)).times do |x| %>
                            <a href="#">
                                <span class="fa fa-star-o"></span>
                            </a>
                        <% end%>
                            </p>
                        </figcaption>
                    </figure>
                </div>
            </div>            
            <div class="col-xs-12 divider text-center">
                <% if current_user.is_student %>
                <div class="bottom">
                    <a class="btn btn-primary btn-twitter btn-sm" href="https://github.com/<%= @user.github_url %>">
                        <i class="fa fa-github"></i>
                    </a>
                    <a class="btn btn-danger btn-sm" rel="publisher"
                       href="https://www.linkedin.com/<%= @user.linkedin_url %>">
                        <i class="fa fa-linkedin"></i>
                    </a>
                    <a class="btn btn-primary btn-sm" rel="publisher"
                        href="http://www.<%= @user.personal_website %>">
                        <i class="glyphicon glyphicon-globe"></i>
                    </a>
                
                </div>
                <% else %>
                    <a class="btn btn-danger btn-sm" rel="publisher"
                       href="https://www.linkedin.com/<%= @user.linkedin_url %>">
                        <i class="fa fa-linkedin"></i>
                    </a>
                    <a class="btn btn-primary btn-sm" rel="publisher"
                        href="http://www.<%= @user.personal_website %>">
                        <i class="glyphicon glyphicon-globe"></i>
                    </a>
                <% end %>
                
            </div>
    	 </div>                 
		</div>
	</div>
</div>