config/routes.rb
Rails.application.routes.draw do
  
  resources :notifications
  resources :comments
  get 'contracts/:id/add' => "contracts#add", as: :add_contract
  get 'contracts/:id/destroy' => "contracts#destroy", as: :destroy_contract
  get 'contracts/:id/start' => "contracts#start", as: :start_contract
  get 'contracts/:id/reset' => "contracts#reset", as: :reset_contract
  get 'contracts/:id/approve' => "contracts#approve", as: :approve_contract
  get 'contracts/:id/finish' => "contracts#finish", as: :finish_contract
  get 'contracts/search' => "contracts#search", as: :search_contract
  get 'profiles/search' => "profiles#search", as: :search_users 
  get 'profiles/progress' => "profiles#progressing", as: :progressing_profiles
  get 'profiles/saved' => "profiles#saved", as: :saved_profiles
  resources :profiles do
    get :autocomplete_skill_tag_name, on: :collection
    get :autocomplete_industry_tag_name, on: :collection
  end

  resources :contracts do
    get :autocomplete_skill_tag_name, on: :collection
  end

  get 'skill_tags/:id/add' => "skill_tags#add", as: :add_skill_tag
  
  devise_for :users, :controllers => { :registrations => "registrations" }
  devise_scope :user do
    get "/login" => "devise/sessions#new"
    delete "/logout" => "devise/sessions#destroy"
  end

  root 'profiles#index'

end

app/models/contract.rb
class Contract < ActiveRecord::Base
	validates :title, :description, presence: true
	validates :pay, numericality: {greater_than_or_equal_to: 0.01}
    has_and_belongs_to_many :users
    has_many :notifications
    has_attached_file :picture, styles: {
      thumb: '130x130>'
    },
    :default_url => '/images/picture/missing.png'
    validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
    has_and_belongs_to_many :skill_tags
    has_many :comments

    def root_comments
        comments.where parent_id: nil
    end
      def self.search(query)
              # where(:title, query) -> This would return an exact match of the query
         where("title like ? OR company like ? OR description like ?", "%#{query}%", "%#{query}%", "%#{query}%") 
      end
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  before_action :set_contract, only: [:show, :edit, :update, :destroy]
  autocomplete :skill_tag, :name

  # GET /contracts
  # GET /contracts.json
  def index
     @contracts = Contract.all.order("created_at DESC").page(params[:page]).per(15)
  end

  # GET /contracts/1
  # GET /contracts/1.json
  def show
      fresh_when([@contract, @contract.skill_tags, @contract.comments, @contract.users])
  end

  # GET /contracts/new
  def new
    @contract = Contract.new
  end

  # GET /contracts/1/edit
  def edit
  end

  # POST /contracts
  # POST /contracts.json
  def create
    # Only companies can create contracts

    if !current_user.is_student
      @contract = Contract.new(contract_params)
      @contract.owner = current_user.id
      current_user.contracts << @contract

      #skills
      
        result = params[:skill_tag_name].split(",")
        result.each do |k|
          skill = SkillTag.find_by_name(k)
          @contract.skill_tags << skill
          @contract.save!
        end
      respond_to do |format|
        if @contract.save
          format.html { redirect_to @contract, notice: 'Contract was successfully created.' }
          format.json { render :show, status: :created, location: @contract }
        else
          format.html { render :new }
          format.json { render json: @contract.errors, status: :unprocessable_entity }
        end
      end
    else
      respond_to do |format|
          format.html { render :index }
          format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contracts/1
  # PATCH/PUT /contracts/1.json
  def update

     result = params[:skill_tag_name].split(",")
        result.each do |k|
          skill = SkillTag.find_by_name(k)
          @contract.skill_tags << skill
          @contract.save!
        end

    respond_to do |format|
      if @contract.update(contract_params)
        format.html { redirect_to @contract, notice: 'Contract was successfully updated.' }
        format.json { render :show, status: :ok, location: @contract }
      else
        format.html { render :edit }
        format.json { render json: @contract.errors, status: :unprocessable_entity }
      end
    end
  end

  def add
    if current_user.is_student 
         respond_to do |format|
             contract = Contract.find(params[:id])
             if !current_user.contracts.include?(contract)
		 company = User.find(contract.owner)
		 #send email to company to notify pending
		 #Larrymailer.contract_pending(current_user, company, contract).deliver_now
      #   company.has_notifications = true
      #   notification = Notification.new
      #   notification.sender = current_user
      #   notification.recipient = company
      #   notification.subject = "#{current_user.first_name} has added your contract!"
      #   notification.contract = contract
      #   notification.body = "#{current_user.first_name} has signaled interest in your contract #{contract.title}."
      #   company.notifications_as_recipient << notification
      #   company.save!
      #   current_user.notifications_as_sender << notification
      #   contract.notifications << notification
      #   contract.save!
                 current_user.contracts << contract
                 current_user.save!
      #           notification.save!
                 format.html { redirect_to contract, notice: 'Contract was successfully added to profile.' }
                 format.json {render :show, status: :ok, location: @contract }
             else
                 format.html { redirect_to contract, notice: 'Contract is already saved' }
                 format.json {render :show, status: :ok, location: @contract }
             end
         end
    end 
  end
  
  # choose a user to start contract
  def start
    @contract = Contract.find(params[:id])
    @contract.worker = params[:worker]
    worker = User.find(@contract.worker)
    #send email to user to note contract accepted
    #Larrymailer.contract_accepted(worker, @contract).deliver_now
         worker.has_notifications = true
         notification = Notification.new
         notification.sender = current_user
         notification.recipient = worker
         notification.subject = "#{current_user.corporation} has designated you for #{@contract.title}!"
         notification.contract = @contract
         notification.body = "#{current_user.corporation} has assigned you to work for #{@contract.title}!"
         worker.notifications_as_recipient << notification
         worker.save!
         current_user.notifications_as_sender << notification
         @contract.notifications << notification
         @contract.save!
                 current_user.save!
                 notification.save!
    @contract.progress = true
    @contract.save!
    respond_to do |format|
             format.html { redirect_to @contract, notice: 'Contract was successfully assigned.' }
             format.json {render :show, status: :ok, location: @contract }
    end
  end

  # Drop worker/student from contract
  def reset
    @contract = Contract.find(params[:id])
    worker = User.find(@contract.worker)
    #send email to user to note contract accepted
    #Larrymailer.contract_accepted(worker, @contract).deliver_now
         worker.has_notifications = true
         notification = Notification.new
         notification.sender = current_user
         notification.recipient = worker
         notification.subject = "#{current_user.corporation} has dropped you from #{@contract.title}!"
         notification.contract = @contract
         notification.body = "#{current_user.corporation} has dropped you to from for #{@contract.title}! You can contact him at #{current_user.email} "
         worker.notifications_as_recipient << notification
         worker.save!
         current_user.notifications_as_sender << notification
         @contract.notifications << notification
         @contract.save!
                 current_user.save!
                 notification.save!
    @contract.progress = false
    @contract.worker = 0;
    @contract.save!
    respond_to do |format|
             format.html { redirect_to @contract, notice: 'Contract worker was successfully dropped.' }
             format.json {render :show, status: :ok, location: @contract }
    end
  end

  # For student to mark as finished
  def finish
    @contract = Contract.find(params[:id])    
    company = User.find(@contract.owner)
    #email company that user has finished work
    #Larrymailer.contract_finished(current_user, company, @contract).deliver_now
         company.has_notifications = true
         notification = Notification.new
         notification.sender = current_user
         notification.recipient = company
         notification.subject = "#{current_user.first_name} has finished your contract!"
         notification.contract = @contract
         notification.body = "#{current_user.first_name} has marked the contract #{@contract.title} done. Please approve it on the contract page."
         company.notifications_as_recipient << notification
         company.save!
         current_user.notifications_as_sender << notification
         @contract.notifications << notification
         @contract.save!
                 current_user.save!
                 notification.save!
    @contract.done = true
    @contract.save!
    respond_to do |format|
             format.html { redirect_to @contract, notice: 'Contract was successfully submitted.' }
             format.json {render :show, status: :ok, location: @contract }
    end
  end

  # For companies to end transaction
  def approve
    @contract = Contract.find(params[:id])
    user = User.find(@contract.worker)
    #send worker email that he will get payed for his approved work
    #Larrymailer.contract_approved(user, @contract).deliver_now
         user.has_notifications = true
         notification = Notification.new
         notification.sender = current_user
         notification.recipient = user
         notification.subject = "#{current_user.corporation} has approved your work for  #{@contract.title}!"
         notification.contract = @contract
         notification.body = "#{current_user.corporation} has approved your work for #{@contract.title}! Your payment will be deposited shortly."
         user.notifications_as_recipient << notification
         user.save!
         current_user.notifications_as_sender << notification
         @contract.notifications << notification
         @contract.save!
                 current_user.save!
                 notification.save!
    @contract.approved = true
    @contract.save!
    respond_to do |format|
      format.html { redirect_to contracts_url, notice: 'Contract was successfully completed. Payment will be sent via email' }
      format.json { head :no_content }
    end
  end

  # DELETE /contracts/1
  # DELETE /contracts/1.json
  def destroy
    @contract.destroy
    respond_to do |format|
      format.html { redirect_to contracts_url, notice: 'Contract was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  # search
  def search
                if params[:search]
                          @contracts = Contract.search(params[:search]).order("created_at DESC").page(params[:page]).per(15)
                else
                          @contracts = Contract.all.order("created_at DESC").page(params[:page]).per(15)
                end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contract
         @contract = Contract.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contract_params
      params.require(:contract).permit(:title, :company, :description, :image_url, :pay, :picture)
    end
end

app/helpers/contracts_helper.rb
module ContractsHelper
  def cache_key_for_contracts
    "contracts-#{Contract.maximum(:updated_at)}-#{Comment.maximum(:updated_at)}"
  end

  def cache_key_for_contract_row(contract)
    "contract-#{contract.id}-#{contract.updated_at}"
  end
end

app/views/contracts/_form.html.erb
<div class="container">
<div class="row">
  
  <%= form_for(@contract) do |f| %>
     <% if @contract.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contract.errors.count, "error") %> prohibited this contract from being saved:</h2>

      <ul>
      <% @contract.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="col-lg-6">
      <div class="well well-sm"><strong><i class="glyphicon glyphicon-ok"></i> Required Field</strong></div>
      <div class="form-group">
        <label for="InputName">Title</label>
        <div class="input-group">
	  <%= f.text_field :title, autocomplete:"off", class:"form-control", placeholder:"Enter Title" %>
          <span class="input-group-addon"><i class="glyphicon glyphicon-ok"></i></span></div>
      </div>
      <%= f.hidden_field :company, value: current_user.corporation %>
      <div class="form-group">
        <label for="InputEmail">Pay</label>
        <div class="input-group">
	  <%= f.text_field :pay, class:"form-control", placeholder:"Enter Pay" %>
          <span class="input-group-addon"><i class="glyphicon glyphicon-ok"></i></span></div>
      </div>
      <div class="form-group">
        <label for="InputEmail">Deadline</label>
        <div class="input-group">
	  <%= f.text_field :deadline, class:"form-control", placeholder:"Enter Pay" %>
          <span class="input-group-addon"><i class="glyphicon glyphicon-ok"></i></span></div>
      </div>
      <div class="form-group">
        <label for="InputMessage">Description</label>
        <div class="input-group">

    <%= f.text_area :description, rows: 6, class:"form-control", placeholder:"Short Description" %>
       
          <span class="input-group-addon"><i class="glyphicon glyphicon-ok"></i></span></div>
      </div>
      <div class="form-group">
        <label for="InputReal">Photo</label>
        <div class="input-group">
          <%= f.file_field :picture, class:"form-control", placeholder:"Contract Image" %>
          <span class="input-group-addon"></span></div>
      </div>
      <div class="form-group">
        <label for="InputReal">Skills</label>
        <div class="input-group">
           <%= autocomplete_field_tag :skill_tag_name, params[:name], autocomplete_skill_tag_name_profiles_path, 'data-delimiter' => ',', :multiple =>true, class:"form-control", placeholder:"Enter your skills" %>
          <span class="input-group-addon"><i class="glyphicon glyphicon-ok"></i></span></div>
      </div>
       <%= f.submit "Create", class:"btn btn-info pull-right"  %>
    
    </div>
 <% end %>
  
</div>

</div>

app/views/contracts/edit.html.erb
<h1 class="page-header">Editing Contract</h1>

<%= render 'form' %>

<%= link_to 'Show', @contract %> |
<%= link_to 'Back', contracts_path %>

app/views/contracts/index.html.erb
<h1 class="page-header">Listing contracts</h1>
<ul class="contracts-list">
    <%= paginate @contracts, :theme => 'twitter-bootstrap-3' %>
<% cache(cache_key_for_contracts) do %>
  <% @contracts.each do |contract| %>
      <% if !contract.approved %>
  <% cache(cache_key_for_contract_row(contract)) do %>
  <li class="contract-li <%= cycle('contract-odd', 'contract-even') %>">
    <div class="contract-box">
      <div class="contract-img">
      </div>
      <div class="contract-text">
	<h4 class="contract-title"><%= contract.title %></h4>
	<div class="contract-description">
	  <h4><%= truncate(strip_tags(contract.description), length: 80) %></h4>
	  <%= link_to 'Show', contract, class:"btn btn-default btn-xs"%>
	</div>
      </div>
    </div>
  </li>
  <% end %>
  <% end %>
  <% end %>
<% end %>
</ul>

app/views/contracts/new.html.erb
<h1 class="page-header">New Contract</h1>

<%= render 'form' %>

<%= link_to 'Back', contracts_path %>

app/views/contracts/search.html.erb
<h1 class="page-header">Search Contracts</h1>
<%= form_tag(search_contract_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Contracts" %>
    <%= submit_tag "Search" %>
<% end %>
<h2>Found <%= pluralize @contracts.total_count , "contract" %>!</h2>
<hr/>
<ul class="contracts-list finished">
    <%= paginate @contracts, :theme => 'twitter-bootstrap-3' %>
    <% @contracts.each do |contract| %>
        <% cache(cache_key_for_contract_row(contract)) do %>
        <li class="contract-li <%= cycle('contract-odd', 'contract-even') %>">
        <div class="contract-box">
            <div class="contract-img">
                <%= image_tag(contract.image_url, class: 'contract-image') %>
            </div>
            <div class="contract-text">
                <h4 class="contract-title"><%= contract.title %></h4>
                <div class="contract-description">
                    <h4><%= truncate(strip_tags(contract.description), length: 80) %></h4>
                    <%= link_to 'Show', contract, class:"btn btn-default btn-xs"%>
                </div>
            </div>
        </div>
        </li>
    <% end %>
    <% end %>
</ul>

app/views/contracts/show.html.erb
<%= stylesheet_link_tag "contract" %>
<div style="overflow: hidden">
<div class="row">
<div class="col-sm-2">
</div>
<div>
</div>
</div>
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-6 col-md-6">
            <div class="well well-sm">
                <div class="row">
                    <div class="col-sm-6 col-md-4">
                        <img src="<%= @contract.picture %>" alt="" class="img-rounded img-responsive" />
                    </div>
                    <div class="col-sm-6 col-md-8">
                        <h4><%= @contract.title %></h4>
                        <small><cite title="San Francisco, USA"><%= @contract.company %>  <i class="glyphicon glyphicon-briefcase">
                        </i></cite></small>
                        <p>
                            <i class="glyphicon glyphicon-star"></i>  Pay: $<%= @contract.pay %>
                            <br />
                            <i class="glyphicon glyphicon-globe"></i> Description: <%= @contract.description %>
                            <br />
                            <i class="glyphicon glyphicon-gift"></i>  Deadline: <%= @contract.deadline %></p>
                        <!-- Split button -->
                        <div class="btn-group">
                            <button type="button" class="btn btn-primary">
                                Skills Required</button>
                            <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                                <span class="caret"></span><span class="sr-only">Social</span>
                            </button>
                            <ul class="dropdown-menu" role="menu">
			       <% @contract.skill_tags.each do |k| %>
			       <li><a href="#"><%= k.name %></a></li>

			       <% end %>
			       
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<% if (current_user.id == @contract.owner) %>
    <%= link_to 'Edit this contract', edit_contract_path, {class: 'btn btn-primary btn-xs'} %>
    <%= link_to 'Delete this contract', destroy_contract_path, {class: 'btn btn-primary btn-xs'} %>
    <% if @contract.progress == false %>
        <hr style="    padding: 0;
        border: none;
        border-top: medium double #333;
        color: #333;
        text-align: center;">
        <% @contract.users.each do |u| %>
            <% if u.is_student %>
                <p><strong><%= u.first_name %></strong> is interested in this contract!</p>
                <%= link_to 'Assign student', start_contract_path(:worker => u.id), {class: 'btn btn-primary btn-xs'} %>
                <%= link_to 'Show student', profile_path(u), {class: 'btn btn-primary btn-xs'} %>
                <hr>
            <% end %>
        <% end %>
    <% else %>
        <p> This contract is under progress! </p>
    <% end %>
<% elsif (current_user.id == @contract.worker && @contract.progress == true && @contract.done == false) %>
    <%= link_to 'Mark finished!', finish_contract_path, {class: 'btn btn-primary btn-xs'}%> 
<% end %>
<% if current_user.is_student %>
	  <%= link_to 'Accept', add_contract_path, class:"btn btn-default btn-lg" %>
  <% end %>
<hr>
<h1 class="page-header">Similar Contracts</h1>
<div class="container">
        <div class="row">
	  <% cache(cache_key_for_contracts) do %>
            <% @contract.skill_tags.includes(:contracts).limit(4).each do |similar| %>
                <% similar.contracts[0..3].each do |c| %>
                   <% if c != @contract %>
            <div class="col-sm-3">
                <div class="card">
                    <canvas class="header-bg" width="250" height="70" id="header-blur"></canvas>
                    <div class="avatar">
                        <%= image_tag(User.find(@contract.owner).avatar.url(:thumb)) %>
                    </div>
                    <div class="content">
                        <h2><%= c.title %></h2>
                        <p><%= link_to "See more", contract_path(c), {class: 'btn btn-primary btn-xs'}%></p>
                    </div>
                </div>
            </div>
                    <% end %>
                <% end %>
            <% end %>
        <% end %>
        </div>
</div>
<hr>
<div>
    <%= link_to("Comment on this contract", {controller: "comments", action: "new", comment: {contract_id: @contract.id}}, class: 'btn btn-primary btn-xs') %>
      </div>

      <div>
                Comments:<br>
                  <%= render @contract.root_comments %>
              </div>
<%= link_to 'Back', contracts_path %>
</div>