config/routes.rb
Rails.application.routes.draw do
  
  resources :notifications
  resources :comments
  get 'contracts/:id/add' => "contracts#add", as: :add_contract
  get 'contracts/:id/destroy' => "contracts#destroy", as: :destroy_contract
  get 'contracts/:id/start' => "contracts#start", as: :start_contract
  get 'contracts/:id/reset' => "contracts#reset", as: :reset_contract
  get 'contracts/:id/approve' => "contracts#approve", as: :approve_contract
  get 'contracts/:id/finish' => "contracts#finish", as: :finish_contract
  get 'contracts/search' => "contracts#search", as: :search_contract
  get 'profiles/search' => "profiles#search", as: :search_users 
  get 'profiles/progress' => "profiles#progressing", as: :progressing_profiles
  get 'profiles/saved' => "profiles#saved", as: :saved_profiles
  resources :profiles do
    get :autocomplete_skill_tag_name, on: :collection
    get :autocomplete_industry_tag_name, on: :collection
  end

  resources :contracts do
    get :autocomplete_skill_tag_name, on: :collection
  end

  get 'skill_tags/:id/add' => "skill_tags#add", as: :add_skill_tag
  
  devise_for :users, :controllers => { :registrations => "registrations" }
  devise_scope :user do
    get "/login" => "devise/sessions#new"
    delete "/logout" => "devise/sessions#destroy"
  end

  root 'profiles#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Atticus</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "notification" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<!-- Added a header for sign in state -->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand brandname" href="/">Atticus</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
	<% if user_signed_in? %>
	<% if current_user.is_student %>
        <li class="navbar-link"><a href="/">Welcome <%= current_user.first_name %>!</a></li>
	<% else %>
	  <li class="navbar-link"><a href="/">Welcome <%= current_user.corporation %> corporation!</a></li>
	<% end %>
    <li>
      <a href="/notifications" style="padding: 0px">
      <button class="btn btn-default btn-lg btn-link" style="font-size:20px;">
              <span class="glyphicon glyphicon-comment"></span>
                </button>
                <% if current_user.has_notifications %>
                  <span class="badge badge-notify">!</span>
                <% end %>
      </a>
    </li>
	<li><%= link_to 'Show Profile', profile_path(current_user) %></li>
	<li><%= link_to 'Edit Account', edit_user_registration_path %></li>
	<li><%= link_to 'Edit Profile', edit_profile_path(current_user) %></li>
	<li class="navbar-link"><%= link_to "Logout", destroy_user_session_path, method: :delete  %></li><% else %>
	<li class="navbar-link"><%= link_to "Sign up", new_user_registration_path  %></li>
	<li class="navbar-link"><%= link_to "Login", new_user_session_path %></li>
	<% end %>
      </ul>
    </div>
  </div>
</nav>
<div class="row">
    <div class="col-sm-3 col-md-2"></div>
    <div class="col-sm-9 col-md-10">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    </div>
</div>

<!-- Sidebar -->
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-3 col-md-2 col-xs-2 sidebar">
      <ul class="nav nav-sidebar">
	<% if user_signed_in? %>
      <% if current_user.is_student %>
	    <li><a href="/profiles">Finished Contracts</a></li>
	    <li><a href="/profiles/progress">Live Contracts</a></li>
	    <li><a href="/profiles/saved">Saved Contracts</a></li>
        <hr>
	    <li><a href="/contracts">All Contracts</a></li>
	    <li><a href="/contracts/search">Search Contracts</a></li>
	    <li><a href="/profiles/search">Search Users</a></li>
      <% else %>
	    <li><a href="/profiles">Pending Contracts</a></li>
	    <li><a href="/profiles/progress">Progressing Contracts</a></li>
	    <li><a href="/profiles/saved">Waiting Contracts</a></li>
        <hr>
	    <li><a href="/contracts">All Contracts</a></li>
	    <li><a href="/contracts/search">Search Contracts</a></li>
	    <li><a href="/profiles/search">Search Users</a></li>
        <li><%= link_to "Create contract", new_contract_path %></li>
      <% end %>
      <% end %>
      </ul>
    </div>
    <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
      <%= yield %>
    </div>
  </div>
</div>
</body>
</html>